name: unit-tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          chmod +x scripts/*.sh
          sudo ./scripts/install_ubuntu_dependencies.sh

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DAT_BUILD_TESTS=ON -DAT_ENABLE_EFFICIENT_RAND=OFF
          make -j

      - name: Run tests
        run: |
          for x in $(find build/bin -name "*_test" | grep -v "audio_interface_test"); do "./$x" || exit 1; done
